### PR TITLE
Adds _Attrib as valid arg to etree._Attrib.update()

### PR DESCRIPTION
**Pull request by funkyfuture**

### CODE REVIEW

**Comment by scoder** [comment]
Alternatively, we could declare `_Attrib` as inheriting from `Mapping[AnyStr, AnyStr]`, right? Don't know what's better.

**Comment by funkyfuture** [comment]
sure, if that alias is applicable consistently, that'd be preferable. i didn't take that course b/c it seemed like a bigger change.

i'd propose to drop the leading underscore though b/c it implies to be 'private' while user code would import that symbol. personally, i'd prefer to name it `Attributes`, but that may be conflicting with the common `lxml` names.

**Comment by scoder** [comment]
It has a leading underscore because users shouldn't care (and shouldn't instantiate it either). For them, it's a mapping.
Therefore, registering it as a `Mapping` seems right (inheriting won't work since it's a static extension type).

**Comment by funkyfuture** [comment]
i'm not sure whether there's a misunderstanding. a user wouldn't instantiate it, but use it in annotations.

but i just noticed it wouldn't be consistent anyway, since there's `_Element` too, see [this example](https://github.com/funkyfuture/delb/blob/main/_delb/nodes.py#L60) where it contrasts `Comment`.

**Comment by scoder** [comment]
`Comment` and `PI` are functions, not classes. The (internal) classes are called `_Comment` and `_ProcessingInstruction`.

**Comment by scoder** [comment]
Annotations should use `Mapping`, not `_Attrib`.

**Comment by funkyfuture** [comment]
> Comment and PI are functions, not classes.

nobody claimed that.

> Annotations should use Mapping, not _Attrib.

why shouldn't i do the following?

```python
from lxml import etree

def do_something(attributes: etree._Attrib) -> etree._Attrib:
    …

element = etree.Element("foo")
element.attrib.update(do_something(element.attrib))
```

**Comment by scoder** [comment]
> > Comment and PI are functions, not classes.

> nobody claimed that.

I was referring to the comparison between `_Element` and `Comment` which lead you to the remark that "it wouldn't be consistent anyway". My response to that is that they are entirely different things. One is an internal implementation class, the other is an API function. Thus the difference in naming. I'm not sure what you are calling "not consistent" here.


> > Annotations should use Mapping, not _Attrib.
> 
> why shouldn't i do the following?
> 
> ```python
> from lxml import etree
> 
> def do_something(attributes: etree._Attrib) -> etree._Attrib:
>     …
> 
> element = etree.Element("foo")
> element.attrib.update(do_something(element.attrib))
> ```

As you wish. But why would you want your code to rely on implementation details of a library that you do not control, if you can just use `Mapping`?

**Pull request merged**
